### ISSUE TITLE
registered user profiles

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#48]
allow updating of personal or lab URLs, emails, address, bios(?)

**Comment by tigerhawkvok** [comment]
Profile display:
- On project
- Created project
- user "metadata"
- Standard outbound links -- use any social media as a guide

Profile edit:
- Link to settings for new password / 2fa
- Hide projects from list view?

Maybe needs new table, or new column in userhandler?

**Comment by mkoo** [comment]
Basically two issues: user profiles (basic information and roles) and then administration of users (separate issue).

Roles: Super admin, PI, Diagnostic Lab PI, project contributor (individuals may have more than one role)

User Basic Information:

- Name
- Address + Phone
- email
- website

**Comment by tigerhawkvok** [comment]
Rough database sketch

[Profile Pages.pdf](https://github.com/AmphibiaWeb/amphibian-disease-tracker/files/244361/Profile.Pages.pdf)

**Comment by tigerhawkvok** [comment]
Features

- [ ] Edit / save UH phone number
- Add / validate / edit social media profiles
  - [x] Google+
  - [x] Facebook
  - [x] Twitter
  - [ ] LinkedIn
  - [ ] User-defined other
- [x] Add/edit Institution name
- [x] Add/edit department name
- [x] Add/edit/validate (via Google Maps) institution/department address
- [x] Public address should have a map linkout
- [x] Department address should update displayed country calling code based on lookup
- [x] Markdown personal profile
- [ ] User profile image
- [ ] References to user should include linkout to this profile
- [x] When viewing own profile, shortcut to copy self-link
- [ ] Privacy toggles for email, phone, department phone (at levels `public`, `members`, `collaborators`)
- [ ] Public phone/email should be obscured behind CAPTCHA (see Project pages)
- [x] Phone numbers should be `tel:` linked on view
- User search
  - [x] Default to search when not logged in
  - [x] Show search icon when logged in or viewing another profile
  - [x] Asynchronous responsive search

On Hold:
- Conversations w/ other users

**Comment by tigerhawkvok** [comment]
Closing as the remaining additions have their own issues.
